name: Report

options:
  bundleIdPrefix: dev.jano.report
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  createIntermediateGroups: true
  deploymentTarget:
    iOS: 15.4

settings:
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES

targets:

  Report:
    type: framework
    platform: iOS
    postCompileScripts:
      - script: swiftlint
        name: Swiftlint
    scheme:
      testTargets:
         - name: ReportTests
           parallelizable: true
           randomExecutionOrder: true
    settings:
       CURRENT_PROJECT_VERSION: 1
       INFOPLIST_FILE: targets/main/Info.plist
       IPHONEOS_DEPLOYMENT_TARGET: 15.4
       PRODUCT_BUNDLE_IDENTIFIER: dev.jano.report
       PRODUCT_NAME: Report
    sources: sources/main
    type: framework

  ReportTests:
    dependencies:
      - target: Report
    platform: iOS
    type: bundle.unit-test
    scheme:
      gatherCoverageData: true
      testTargets: 
        - name: ReportTests
          parallelizable: true
          randomExecutionOrder: true
    settings:
      INFOPLIST_FILE: targets/tests/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: dev.jano.report.tests
    sources:
      - sources/tests
