name: Report

options:
  bundleIdPrefix: dev.jano.report
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  createIntermediateGroups: true
  deploymentTarget:
    iOS: 15.4

settings:
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
    DEVELOPMENT_TEAM: PPSF6CNP8Q

targets:

  Report:
    type: framework
    platform: iOS
    sources: 
      - sources/main

  ReportTests:
    type: bundle.unit-test
    platform: iOS
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: es.com.jano.report.tests
    sources:
      - sources/tests
    dependencies:
      - target: Report
