name: Swift
on: [push]
jobs:

  build:
    runs-on: macOS-latest
    steps:
      
      - name: Trust GitHub SSH keys
        run: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
          
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa 
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        run: swiftlint
      
      - name: Use latest Swift version
        uses: fwal/setup-swift@v1
        
      - name: Build for iOS
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -scheme Report -destination "platform=iOS Simulator,OS=latest,name=iPhone 13" | xcpretty

      - name: Run iOS tests
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -scheme Report -destination "platform=iOS Simulator,OS=latest,name=iPhone 13" | xcpretty
